eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

feign:
  hystrix:
    enabled: true

server:
  port: 8765
spring:
  application:
    name: service-feign

logging:
  level: debug